version: '3'
services:
  webrole:
    image: fsc/selfie-share-webrole
    ports:
     - "3000:3000"
    depends_on:
      - mysql
    container_name: webrole
    networks:
      - custom

  workerrole:
    image: fsc/selfie-share-workerrole
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - custom
    container_name: workerrole

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
     "MYSQL_ROOT_PASSWORD": "password"
    container_name: mysql
    networks:
      - custom
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:

networks:
  custom:
